config/routes.rb
Rails.application.routes.draw do

 devise_for :admins, :controllers => {
    :sessions =>'admins/sessions'
  }

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'albums#index'




  # エンドユーザー
  resources :albums, only: [:show] do 
    resource :cart_albums, only: [:create, :destroy]
  end

  match 'cart_albums/edit' => 'cart_albums#update_all', :as => 'update_all', :via => :put

  resources :customers, only: [:show, :edit, :update]
  post 'customers/:id/delete' => 'customers#delete', as: 'customer_delete'

  namespace :customers do
    resources :orders, only: [:new, :create, :update] do
        collection do
        post :confirm
        get :complete
        end
    end
    resource :order_albums, only: [:create]
  end

  resources :contacts, only: [:new, :create] do 
    collection do 
      post :confirm
      get :complete
    end
  end


# 管理者

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    post 'customers/:id/delete' => 'customers#delete'
  end

  namespace :admins do
    namespace :customers do
      get 'orders/destroy'
      get 'orders/update' => 'orders#update', as: 'orderup'
    end
  end

  namespace :admins do
    resources :albums do
      collection do
        get :confirm
      end
    end
  end

    namespace :albums do
      resources :discs, only: [:create, :update, :destroy]
      namespace :discs do
        resources :songs, only: [:create, :update, :destroy]
        resources :singers, only: [:create, :update, :destroy]
      end
    end

    namespace :customers do
      resources :orders, only: [:destroy]
    end

    namespace :admins do
      resources :contacts, only: [:index, :show, :destroy]
    end

    match 'orders/edit' => 'admins/customers/orders#update', :as => 'orders_update_all', :via => :put

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && deleted.blank?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_albums, dependent: :destroy
  accepts_nested_attributes_for :cart_albums
  has_many :orders, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :postalcode, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
  validates :adress, presence: true
  validates :phone, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/}
  
end

app/controllers/admins/customers/customers_controller.rb
class Admins::Customers::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @Customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.update(customer_params)
    if customer.save
      redirect_to root_path
    else
      render 'admins/customers/edit'
    end
  end

  def destroy
    customer = Customer.find(params[:id])
    if customer.destroy(customer_params)
      redirect_to root_path
    else
      render 'admins/customer/edit'
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :phone, :postalcode, :adress)
  end

end

app/controllers/admins/customers/orders_controller.rb
class Admins::Customers::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def update
    params.permit!
    params['order'].keys.each do |id|
      @order = Order.find(id.to_i)
      @order.update_attributes(params['order'][id])
    end
    redirect_to admins_customer_path(@order.customer)
		
	end


  def destroy
  end


  def order_params
    params.require(:order).permit( :first_name, :last_name, :postalcode, :order_adress, :payway, :order_status, order_albums_attributes: [:id, :order_id, :album_name, :jacket_image, :price, :stock_quantity, :genre, :label])
  end


end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@customers = Customer.where(deleted: nil)
    @deleted_customers = Customer.where(deleted: true)
  end

  def show
  	@customer = Customer.find(params[:id])
  	@cart = CartAlbum.where(customer_id:@customer.id)
    @order = Order.where(customer_id: @customer.id)
  end

  def edit
    @customer = Customer.find(params[:id])
    @orders = Order.where(customer_id: params[:id])
  end

  def update
     customer = Customer.find(params[:id])
     if  customer.update(customer_params)
       redirect_to admins_customer_path(params[:id])
     else
       render 'edit'
     end
  end

  def delete
    customer = Customer.find(params[:id])
    customer.update(deleted: true)
    redirect_to admins_customers_path
  end


  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :phone, :postalcode, :adress)
  end
end

app/controllers/customers/base.rb
class Customer::Base < ApplicationController

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/order_albums_controller.rb
class OrderAlbumsController < ApplicationController

  def create
    order = Order.where(customer_id: current_customer.id).last
    # add cart_album status below
    cart_albums = CartAlbum.where(customer_id: current_customer.id)
    orders = {
      OrderAlbum.album_name = cart_album.album_name
      OrderAlbum.jacket_image = cart_album.jacket_image
      OrderAlbum.price = cart_album.price
      OrderAlbum.stock_quantity = cart_album.stock_quantity
      OrderAlbum.genre = cart_album.genre
      OrderAlbum.label = cart_album.label
    }
    order_album = OrderAlbum.new(orders)
    binding.pry
    order_album.save
    redirect_to complete_customers_orders_path
  end

end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController

	before_action :login_check, only: [:new, :confirm, :create]

	def new
		@order = Order.new
    @order.order_albums.build
		@customer = current_customer
		@cart_album = CartAlbum.where(customer_id:@customer.id)
	end

	def confirm
		@order = Order.new(order_params)
		@customer = current_customer
		@cart_album = CartAlbum.where(customer_id:@customer.id)
	end

	def create
		order = current_customer.orders.new(order_params)
    order.purchase_date = order.created_at
    order.first_name_kana = current_customer.first_name_kana
    order.last_name_kana = current_customer.last_name_kana
		cart_album = CartAlbum.where(customer_id: current_customer.id)

    total = 0
    cart_album.each do |c|
    	taxprice = c.album.price * 1.08 * c.order_quantity
      total += taxprice
    end

		order.subtotal = total
    cart_album.each do |c|
      order_album = order.order_albums.build
      order_album.album_name = c.album.album_name
      order_album.jacket_image_id = c.album.jacket_image_id
      order_album.price = c.album.price
      order_album.stock_quanitity = c.order_quantity
      order_album.genre = c.album.genre
      order_album.label = c.album.label
      order_album.save

    end
		if order.save
      cart_album = cart_album.where(customer_id: current_customer.id)
      cart_album.each do |cart|
        cart.album.stock_quantity = cart.album.stock_quantity - cart.order_quantity
        cart.album.save
        cart.destroy
      end
    end

		redirect_to complete_customers_orders_path
	end
	


	private

	def login_check
		unless customer_signed_in?
			flash[:alert] = "ログインしてください"
			redirect_to root_path
		end
	end

	def order_params
    	params.require(:order).permit( :first_name, :last_name, :postalcode, :order_adress, :payway, :order_status, order_albums_attributes: [:id, :order_id, :album_name, :jacket_image, :price, :stock_quantity, :genre, :label])
  	end



end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

   # GET /resource/password/edit?reset_password_token=abcdef
   def edit
     super
     @pw_new = Customer.password.new
   end

   # PUT /resource/password
   def update
     super
   end

  # protected

   def after_resetting_password_path_for(resource)
     super(resource)
   end

   # The path used after sending reset password instructions
   def after_sending_reset_password_instructions_path_for(resource_name)
     super(resource_name)
   end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:show,:edit]
  def show
    @customer = current_customer
    @cart = CartAlbum.where(customer_id:current_customer.id)
    @order = Order.where(customer_id: current_customer.id)
  end

  def edit
    @customer = Customer.find(params[:id])
    @cart = CartAlbum.where(customer_id: params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to customer_path(customer.id)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def delete
    customer = Customer.find(params[:id])
    customer.update(deleted: true)
    render 'complete'
  end

  def complete
  end


  def destroy
    customer = Customer.find(params[:id])
    if customer.destroy(customer_params)
      redirect_to new_customer_registration_path 
    else
      flash[:error] = "Something went wrong"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :phone, :postalcode, :adress, cart_albums_attributes: [:id, :order_quantity])
  end

  def cart_album_params
    params.require(:cart_album).permit(:customer_id, :album_id, :order_quantity)
  end

end

app/helpers/admins/customers/customers_helper.rb
module Admins::Customers::CustomersHelper
end

app/helpers/admins/customers/orders_helper.rb
module Admins::Customers::OrdersHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<section class="page">                                                                   
  <h2 class="page__title">会員情報編集</h2>
  <%= form_for(customer) do |c| %>
               
    <!-- 姓（漢字） -->
    <div class="form__row">
      <label class="form__label">姓</label>
      <%= c.text_field :last_name, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>  
               
    <!-- 名（漢字） -->
    <div class="form__row">
      <label class="form__label">名</label>
      <%= c.text_field :first_name, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>  
               
    <!-- セイ -->
    <div class="form__row">
      <label class="form__label">セイ</label>
      <%= c.text_field :last_name_kana, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>  
               
    <!-- メイ -->
    <div class="form__row">
      <label class="form__label">メイ</label>
      <%= c.text_field :first_name_kana, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>  

    <!-- メールアドレス -->
    <div class="form__row">
      <label class="form__label">メールアドレス</label>
      <%= c.email_field :email, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>

    <!-- phone -->
    <div class="form__row">
      <label class="form__label">電話番号</label>
      <%= c.text_field :phone, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>

    <!-- 郵便番号 -->
    <div class="form__row">
      <label class="form__label">郵便番号</label>
      <%= c.text_field :postalcode, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>

    <!-- 住所 -->
    <div class="form__row">
      <label class="form__label">住所</label>
      <%= c.text_field :adress, autofocus: true, class:"form__field" %>
      <% if alert %>
        <p class="form__alert alert alert-error"><%= alert %></p>
      <% else %>
        <p class="form__condition">*注意書きが入ります。</p>
      <% end %>
    </div>
           
    <!-- 変更ボタン -->
    <%= c.submit "変更完了", class:"btn btn__login" %>
  <% end %>
  
  <!-- カートアルバム数量変更フォーム -->
</div>
</section>                                                                               

app/views/customers/complete.html.erb
<section class="page">

	<h2 class="page__title">退会手続き完了</h2>

	<div>
	<p>退会手続きが完了しました。<p>
	<p>ホーム画面に戻ってください。</p>

	<%= link_to "ホームへ" , destroy_customer_session_path, :method => :delete, class:"contact__link" %>
	<div>

</section>


app/views/customers/edit.html.erb
<%= render 'form', customer: @customer  %>
<p class="btn btn__login"><%= link_to '退会する', customer_delete_path(current_customer.id), method: :post , 'data-confirm' => "ほんまに退会しますか？？", class:"btn btn__link" %></p>

app/views/customers/show.html.erb
<%= render 'templates/customer_show_infos', customer:@customer %>
<div class="btn__box">
  <p class="btn btn__login"><%= link_to '編集する', edit_customer_path(current_customer.id), class:"btn btn__link" %></p>
  <% if @cart.present? %>
  <p class="btn btn__login"><%= link_to '購入ページに行く', new_customers_order_path, class:"btn btn__link", data: {"turbolinks"=>false} %></p>
  <% end %>
</div>