config/routes.rb
Rails.application.routes.draw do

 devise_for :admins, :controllers => {
    :sessions =>'admins/sessions'
  }

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'albums#index'




  # エンドユーザー
  resources :albums, only: [:show] do 
    resource :cart_albums, only: [:create, :destroy]
  end

  match 'cart_albums/edit' => 'cart_albums#update_all', :as => 'update_all', :via => :put

  resources :customers, only: [:show, :edit, :update]
  post 'customers/:id/delete' => 'customers#delete', as: 'customer_delete'

  namespace :customers do
    resources :orders, only: [:new, :create, :update] do
        collection do
        post :confirm
        get :complete
        end
    end
    resource :order_albums, only: [:create]
  end

  resources :contacts, only: [:new, :create] do 
    collection do 
      post :confirm
      get :complete
    end
  end


# 管理者

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    post 'customers/:id/delete' => 'customers#delete'
  end

  namespace :admins do
    namespace :customers do
      get 'orders/destroy'
      get 'orders/update' => 'orders#update', as: 'orderup'
    end
  end

  namespace :admins do
    resources :albums do
      collection do
        get :confirm
      end
    end
  end

    namespace :albums do
      resources :discs, only: [:create, :update, :destroy]
      namespace :discs do
        resources :songs, only: [:create, :update, :destroy]
        resources :singers, only: [:create, :update, :destroy]
      end
    end

    namespace :customers do
      resources :orders, only: [:destroy]
    end

    namespace :admins do
      resources :contacts, only: [:index, :show, :destroy]
    end

    match 'orders/edit' => 'admins/customers/orders#update', :as => 'orders_update_all', :via => :put

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/album.rb
class Album < ApplicationRecord
  # attachment
  attachment :jacket_image

  # association
  has_many :discs, inverse_of: :album 
  has_many :album_singers, inverse_of: :album
  has_many :singers, through: :album_singers
  has_many :cart_albums, dependent: :destroy

  # cocoon
  accepts_nested_attributes_for :discs , allow_destroy: true
  accepts_nested_attributes_for :album_singers, allow_destroy: true
  accepts_nested_attributes_for :singers
  accepts_nested_attributes_for :cart_albums
  
  validates :album_name, presence: true
  validates :jacket_image, presence: true
  validates :price, presence: true
  validates :stock_quantity, presence: true
  validates :sales_status, presence: true
  validates :genre, presence: true
  validates :jacket_image, presence: true
  validates :label, presence: true
  
  def self.search(search)
    if search
      where(["album_name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
  
  
end

app/models/album_singer.rb
class AlbumSinger < ApplicationRecord
  belongs_to :album
  belongs_to :singer
  accepts_nested_attributes_for :singer, reject_if: :all_blank
end

app/models/album_song.rb
class AlbumSong < ApplicationRecord

  belongs_to :disc
  belongs_to :song
  accepts_nested_attributes_for :song, reject_if: :all_blank
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_album.rb
class CartAlbum < ApplicationRecord
	belongs_to :customer
	belongs_to :album
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true
  validates :email, presence: true
  validates :content, presence: true

  validates_acceptance_of :confirming
  after_validation :check_confirming

   def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && deleted.blank?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_albums, dependent: :destroy
  accepts_nested_attributes_for :cart_albums
  has_many :orders, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :postalcode, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
  validates :adress, presence: true
  validates :phone, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/}
  
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :album
  has_many :album_songs, dependent: :destroy
  has_many :songs, through: :album_songs 
  accepts_nested_attributes_for :album_songs, allow_destroy: true
  accepts_nested_attributes_for :songs



end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_albums, dependent: :destroy
  belongs_to :customer

  validates :last_name, presence: true
  validates :first_name, presence: true
# validates :postalcode, presence: true
  validates :order_adress, presence: true
  validates_acceptance_of :confirming

  # cocoon
  accepts_nested_attributes_for :order_albums, allow_destroy: true

  after_validation :check_confirming

   def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
   end

end

app/models/order_album.rb
class OrderAlbum < ApplicationRecord

  belongs_to :order

  attachment :jacket_image

end

app/models/singer.rb
class Singer < ApplicationRecord

  has_many :album_singers, dependent: :destroy
  has_many :albums, through: :album_singers
  validates :singer_name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :album_songs, dependent: :destroy
  has_many :discs, through: :album_songs
  validates :song_title, presence: true
  

end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@contacts = Contact.all
  end

  def show
  	@contact = Contact.find(params[:id])
  end

  def destroy
  	contact = Contact.find(params[:id])
  	contact.destroy
  	redirect_to admins_contacts_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def confirm
		@contact = Contact.new(contact_params)

		if @contact.valid?
			render :action => 'confirm'
		else
			render :action => 'new'
		end
	end


	def create
		contact = Contact.new(contact_params)
		contact.save
		redirect_to complete_contacts_path
	end


  private
  def contact_params
    params.require(:contact).permit(:name, :name_kana, :title, :content, :email)
  end

end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/costomers_helper.rb
module CostomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/admins/contacts/index.html.erb
<section>

	<h2 class="page__title">お問い合わせ一覧</h2>

	<div class="page__content">

	<% @contacts.each do |contact| %>
	<div class="contact">
		<div class="contact__left">
			<p><%= contact.name %></p>
			<p><%= contact.name_kana %></p>
			<p><%= contact.email %></p>
			<p><%= contact.title %></p>
		</div>


		<div class="contact__right">
			<p><%= contact.created_at.strftime('%Y/%m/%d') %></p>
			<p class="btn btn__login"><%= link_to "詳細を見る", admins_contact_path(contact.id) %></p>
		</div>

	</div>
	<% end %>

	</div>
</section>

app/views/admins/contacts/show.html.erb
<section class="page">
<h2 class="page__title">お問い合わせ詳細</h2>


<div class="contact_show">

  <div class="form__row">
  	<p>名前（漢字）：</p>
    <%= @contact.name %>
  </div>

  <div class="form__row">
  	<p>名前（カナ）：</p>
    <%= @contact.name_kana %>
  </div>


<div class="form__row">
	<p>メールアドレス：</p>
    <%= @contact.email %>
 </div>


<div class="form__row">
	<p>タイトル：</p>
    <%= @contact.title %>
  </div>

  <div class="form__row">
  	<p>本文：</p>
    <%= @contact.content %>
  </div>

</div>

<div class="btn btn__login">
  <%= link_to "削除", admins_contact_path(@contact.id), method: :delete, 'data-confirm' => "本当に削除しますか？" %>
</div>

</section>

app/views/contacts/complete.html.erb
<section class="page">

	<h2 class="page__title">お問い合わせ</h2>

	<div>
	<p>送信完了しました。<p>
	<p>お問い合わせ内容確認次第、<br>3営業日以内に担当から記入メールアドレス宛にご連絡いたします。</p>

	<%=link_to "ホームへ", "/", class:"contact__link" %>
	<div>

</section>

app/views/contacts/confirm.html.erb
<section class="page">
<h2 class="page__title">お問い合わせ</h2>
<div class="page__content">
<%= form_for(@contact) do |f| %>

  <div class="form__row">
    <%= f.label :送信者名（漢字）, class:"form__label" %><br>
    <%= f.text_field :name, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>

  <div class="form__row">
    <%= f.label :送信者名（カナ）, class:"form__label" %><br>
    <%= f.text_field :name_kana, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>


<div class="form__row">
    <%= f.label :メールアドレス, class:"form__label" %><br>
    <%= f.text_field :email, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>


<div class="form__row">
    <%= f.label :件名, class:"form__label" %><br>
    <%= f.text_field :title, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>

  <div class="form__row">
    <%= f.label :本文, class:"form__label" %><br>
    <%= f.text_area :content, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>



  <p>記入内容に誤りがない場合は、送信ボタンを押してください。</p>
  <div class="actions">
    <%= f.submit "送信", class:"btn btn__signup" %>
  </div>

<% end %>

</div>
</section>

app/views/contacts/new.html.erb
<section class="page">
<h2 class="page__title">お問い合わせ</h2>
<div class="page__content">
<%= form_for(@contact, :url => confirm_contacts_path) do |f| %>

  <div class="form__row">
    <%= f.label :送信者名（漢字）, class:"form__label" %><br>
    <%= f.text_field :name, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>

  <div class="form__row">
    <%= f.label :送信者名（カナ）, class:"form__label" %><br>
    <%= f.text_field :name_kana, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>


<div class="form__row">
    <%= f.label :メールアドレス, class:"form__label" %><br>
    <%= f.text_field :email, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>


<div class="form__row">
    <%= f.label :件名, class:"form__label" %><br>
    <%= f.text_field :title, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>

  <div class="form__row">
    <%= f.label :本文, class:"form__label" %><br>
    <%= f.text_area :content, class:"form__field" %>
      <p class="form__alert alert alert-error"><%= alert %></p>
      <p class="form__condition">*注意書きが入ります。</p>
  </div>




  <div class="actions">
    <%= f.submit "確認", class:"btn btn__signup" %>
  </div>

<% end %>

</div>
</section>