config/routes.rb
Rails.application.routes.draw do

 devise_for :admins, :controllers => {
    :sessions =>'admins/sessions'
  }

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'albums#index'




  # エンドユーザー
  resources :albums, only: [:show] do 
    resource :cart_albums, only: [:create, :destroy]
  end

  match 'cart_albums/edit' => 'cart_albums#update_all', :as => 'update_all', :via => :put

  resources :customers, only: [:show, :edit, :update]
  post 'customers/:id/delete' => 'customers#delete', as: 'customer_delete'

  namespace :customers do
    resources :orders, only: [:new, :create, :update] do
        collection do
        post :confirm
        get :complete
        end
    end
    resource :order_albums, only: [:create]
  end

  resources :contacts, only: [:new, :create] do 
    collection do 
      post :confirm
      get :complete
    end
  end


# 管理者

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    post 'customers/:id/delete' => 'customers#delete'
  end

  namespace :admins do
    namespace :customers do
      get 'orders/destroy'
      get 'orders/update' => 'orders#update', as: 'orderup'
    end
  end

  namespace :admins do
    resources :albums do
      collection do
        get :confirm
      end
    end
  end

    namespace :albums do
      resources :discs, only: [:create, :update, :destroy]
      namespace :discs do
        resources :songs, only: [:create, :update, :destroy]
        resources :singers, only: [:create, :update, :destroy]
      end
    end

    namespace :customers do
      resources :orders, only: [:destroy]
    end

    namespace :admins do
      resources :contacts, only: [:index, :show, :destroy]
    end

    match 'orders/edit' => 'admins/customers/orders#update', :as => 'orders_update_all', :via => :put

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/album.rb
class Album < ApplicationRecord
  # attachment
  attachment :jacket_image

  # association
  has_many :discs, inverse_of: :album 
  has_many :album_singers, inverse_of: :album
  has_many :singers, through: :album_singers
  has_many :cart_albums, dependent: :destroy

  # cocoon
  accepts_nested_attributes_for :discs , allow_destroy: true
  accepts_nested_attributes_for :album_singers, allow_destroy: true
  accepts_nested_attributes_for :singers
  accepts_nested_attributes_for :cart_albums
  
  validates :album_name, presence: true
  validates :jacket_image, presence: true
  validates :price, presence: true
  validates :stock_quantity, presence: true
  validates :sales_status, presence: true
  validates :genre, presence: true
  validates :jacket_image, presence: true
  validates :label, presence: true
  
  def self.search(search)
    if search
      where(["album_name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
  
  
end

app/models/album_singer.rb
class AlbumSinger < ApplicationRecord
  belongs_to :album
  belongs_to :singer
  accepts_nested_attributes_for :singer, reject_if: :all_blank
end

app/models/album_song.rb
class AlbumSong < ApplicationRecord

  belongs_to :disc
  belongs_to :song
  accepts_nested_attributes_for :song, reject_if: :all_blank
end

app/models/cart_album.rb
class CartAlbum < ApplicationRecord
	belongs_to :customer
	belongs_to :album
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true
  validates :email, presence: true
  validates :content, presence: true

  validates_acceptance_of :confirming
  after_validation :check_confirming

   def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && deleted.blank?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_albums, dependent: :destroy
  accepts_nested_attributes_for :cart_albums
  has_many :orders, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :postalcode, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
  validates :adress, presence: true
  validates :phone, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/}
  
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :album
  has_many :album_songs, dependent: :destroy
  has_many :songs, through: :album_songs 
  accepts_nested_attributes_for :album_songs, allow_destroy: true
  accepts_nested_attributes_for :songs



end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_albums, dependent: :destroy
  belongs_to :customer

  validates :last_name, presence: true
  validates :first_name, presence: true
# validates :postalcode, presence: true
  validates :order_adress, presence: true
  validates_acceptance_of :confirming

  # cocoon
  accepts_nested_attributes_for :order_albums, allow_destroy: true

  after_validation :check_confirming

   def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
   end

end

app/models/order_album.rb
class OrderAlbum < ApplicationRecord

  belongs_to :order

  attachment :jacket_image

end

app/models/singer.rb
class Singer < ApplicationRecord

  has_many :album_singers, dependent: :destroy
  has_many :albums, through: :album_singers
  validates :singer_name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :album_songs, dependent: :destroy
  has_many :discs, through: :album_songs
  validates :song_title, presence: true
  

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/costomers_helper.rb
module CostomersHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matsumoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
   <header class="header">
      <h1 class="header__title">
      <% if customer_signed_in? %>
        <%=link_to "松本商店", root_path %>
      <% elsif admin_signed_in? %>
        <%=link_to "松本商店", admins_albums_path %>
      <% end %>
      </h1>
      <nav class="header__navs">
        <ul class="header__nav">
        <!--エンドユーザーログイン時 -->
        <% if customer_signed_in? %>
     	  <li class="header__item">
              <%= link_to "ホーム", root_path %>  
          </li>
     	  <li class="header__item">
              <%= link_to "マイページ" , customer_path(current_customer.id) , data: {"turbolinks"=>false}  %>  
          </li>
	  <li class="header__item">
              <%= link_to "お問い合わせ", new_contact_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "ログアウト" , destroy_customer_session_path, :method => :delete %>  
          </li>
          <!--管理者ログイン時 -->
          <% elsif admin_signed_in? %>
        <li class="header__item__admin">
              管理者がログインしています。
          </li>
     	  <li class="header__item">
              <%= link_to "商品一覧", admins_albums_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "ユーザー一覧" , admins_customers_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "商品追加" , new_admins_album_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "お問い合わせ一覧", admins_contacts_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "ログアウト",  destroy_admin_session_path, :method => :delete  %>  
          </li>
          <!--非ログイン時 -->
          <% else %>
     	  <li class="header__item">
              <%=link_to "ホーム", root_path %>
          </li>
     	  <li class="header__item">
              <%= link_to "ログイン", new_customer_session_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "新規登録", new_customer_registration_path  %>  
          </li>
     	  <li class="header__item">
              <%= link_to "お問い合わせ", new_contact_path  %>  
          </li>
        <% end %>

        </ul>      
      </nav>
   </header>
    <%= yield %>
  </body>
</html>

app/views/templates/_album_all.html.erb
<section class="page">
  <div class="page__search">
    <p>商品検索</p>
    <%= form_tag(root_path, :method => "get") do %>
      <%= text_field_tag :search %>
      <%= submit_tag "検索", :album_name =>nil %>
    <% end %>
  </div>
  <h2 class="page__title">商品一覧</h2>
  <div class="page__album">
    <% @albums.each do |album| %>
    <div class="album__wrapper">
      <%= link_to(album_path(album), data: {"turbolinks"=>false}) do %>
      <div class="album__img"><%= attachment_image_tag album, :jacket_image , :fill,250,250  %></div>
      <div class="album__title"><%= album.album_name %></div>
      <div class="album__singer">
        <%= album.singers.first.singer_name %>
      </div>
      <% end %>
    </div>
    <% end %>
  <div class="page___pagination">
    <%= paginate @albums, class: "paginate" %>
  </div>
</section>

app/views/templates/_customer_show_cart.html.erb
<div id="cart" class="customer__carts">                                            
  <% @cart.each do |cart| %>
  <div class="customer__cart">
    <div class="customer__cart customer__cart--id"><%= cart.album.id %></div>
    <div class="customer__cart customer__cart--img"><%= attachment_image_tag cart.album, :jacket_image %></div>
    <div class="customer__cart customer__cart--name"><%= cart.album.album_name %></div>
    <div class="customer__cart customer__cart--singer"><%= cart.album.singers.first.singer_name %></div>
    <div class="customer__cart customer__cart--label"><%= cart.album.label %></div>
    <div class="customer__cart customer__cart--price"><%= cart.album.price %></div>
    <div class="customer__cart customer__cart--quantity"><%= cart.album.stock_quantity %></div>
  </div>
  <% end %>
</div><!-- customer__carts -->

app/views/templates/_customer_show_infos.html.erb
<div class="page">
<h2 class="page__title">マイページ</h2>
<div class="customer__wrapper">
  <div class="customer__tabs">
    <div class="customer__tab is_selected">アカウント情報</div>
    <div class="customer__tab">カート商品一覧</div>
    <div class="customer__tab">購入履歴</div>
  </div><!-- customer__tabs -->

  <div id="info" class="customer__infos is_active customer__content">
    <div class="customer__info">
      <label class="customer__info--label">姓</label>
      <p class="customer__info--item"><%= @customer.last_name %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">名</label>
      <p class="customer__info--item"><%= @customer.first_name %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">セイ</label>
      <p class="customer__info--item"><%= @customer.last_name_kana %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">メイ</label>
      <p class="customer__info--item"><%= @customer.first_name_kana %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">メールアドレス</label>
      <p class="customer__info--item"><%= @customer.email %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">電話番号</label>
      <p class="customer__info--item"><%= @customer.phone %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">郵便番号</label>
      <p class="customer__info--item"><%= @customer.postalcode %></p>
    </div>
    <div class="customer__info">
      <label class="customer__info--label">住所</label>
      <p class="customer__info--item"><%= @customer.adress %></p>
    </div>

  </div><!-- cutomer__infos --> 


  <%= form_for :cart_albums, url: update_all_path, :html => { :method => :put } do |f| %>
  <div id="cart" class="customer__carts customer__content">
    <% if @cart.present? %>
    <% @cart.each do |c| %>
    <div class="customer__cart">
      <div class="customer__cart--left">
      <p class="customer__cart--item"><%= attachment_image_tag c.album, :jacket_image%></p>
      </div>
      <div class="customer__cart--right">
        <p class="customer__cart--item carting"><label>アルバム名：</label><%= c.album.album_name %></p>
        <p class="customer__cart--item carting"><label>アーティスト名：<label><%= c.album.singers.first.singer_name %></p>
        <p class="customer__cart--item carting"><label>レーベル名：</label><%= c.album.label %></p>
        <p class="customer__cart--item carting"><label>価格：</label><%= c.album.price %></p>
        <%= fields_for 'cart[]', c do |cart_fields| %>
          <%= cart_fields.number_field :order_quantity, class:"form__field" %>

        <p class="customer__cart--item carting"><label>カート数量：</label><%= c.order_quantity %></p>
        <%= link_to "削除", album_cart_albums_path(c.album), method: :delete, data: { confirm: '本当に消しますか？' } %>
        <% end %>

      </div>
      
    </div>
    
    <% end %>

    <%= f.submit '数量変更完了', class:"btn__login btn" %>
  <% end %>
  <% end %>

  </div><!-- customer__carts -->

  <div id="order" class="customer__orders customer__content">
  <% @order.each do |order| %>
    <div class="customer__order">
      <div class="customer__order--wrapper">
        <div class="customer__order--infos">
          <div class="customer__order--top">
            <div class="order__person">
              <label>購入者名：</label>
              <p class="customer__order--date"><%= order.first_name %></p>
              <p class="customer__order--date"><%= order.last_name %></p>
            </div>
            <div class="order__date">
              <label>購入日：</label>
              <p class="customer__order--date"><%= order.created_at.strftime("%Y-%m-%d") %></p>
            </div>
          </div>
          <div class="order__bottom">
            <p class="customer__order--adress"><label>発送先：</label><%= order.order_adress %></p>
            <p class="customer__order--price"><label>小計：</label><%= order.subtotal %></p>
            <p class="customer__order--price"><label>送料込みの総計:</label><%= order.subtotal + 500 %></p>
          <div class="customer__order--status">
            <label>配達状況：</label>
            <%= order.order_status %>
          </div>
          <% if order.order_albums.presence %>
            <% order.order_albums.each do |oa| %>
            <div class="customer__order--items">
              <!-- @orders.each do |order| -->
              <div class="customer__order--image">
                <%= attachment_image_tag oa, :jacket_image %>
              </div>
              <div class="order__inner">
                <div class="customer__order--name"><label>アルバム名：</label><%= oa.album_name %></div>
                <div class="customer__order--quantity"><label>注文数：</label><%= oa.stock_quanitity %></div>
                <div class="customer__order--subprice"><label>値段：</label><%= oa.price %></div>
              </div>
            </div>
            <% end %>
          <% end %>
      <p class="customer__order--item"></p>
      </div><!-- customer__order-wraooer -->
    </div><!-- customer__order -->
    </div>
  <% end %>  
  </div><!-- order_bottom -->
  </div><!-- cutomer__orders --> 
</div><!-- page -->

app/views/templates/album_all.html.erb
<h2 class="page__title">商品一覧</h2>
<div class="album__wrapper">
  <% @albums.each do |album| %>
  <div class="album__box">
    <div class="album__img"></div>
    <div class="album__title"><%= album.album_name %></div>
    <div class="album__singer"><%= album.album_singer.singer.singer_name %></div>
  </div>
</div>